---
title: "movingAverage"
author: "yy"
date: "2019³â 11¿ù 28ÀÏ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars, echo = FALSE}
library(ggplot2)
library(dplyr)
library(maps)
library(tidyverse)
library(rvest)
library(ggmap)
library(stringr)
library(gridExtra)
library(pander)
library(ggseas)
library(reshape2)
library(pracma)
library(readxl)
library(lubridate)
```
# Train

```{r, echo = FALSE}

for (i in c(0:9)){
  name = paste0("t_",i,"_train.csv")
  df = read.csv(name)
  df$Time = seq(0,nrow(df)-1)
  df$Action = as.factor(df$Action)
  g = ggplot(aes(x = df$Time, y = df$Price), data = df) +
        geom_line() +
        geom_point(aes(color = Action),size = 1) +
        theme_bw() +
        labs(title = paste0("train ",i), x = "Input", y = "Price")
  print(g)
}


```


# Validation
```{r, echo = FALSE}
prof_vec = c()

for (i in c(0:29)){
  name = paste0("t_",i,"_test.csv")
  df = read.csv(name)
  df$Time = seq(0,nrow(df)-1)
  df$Action = as.factor(df$Action)
  g = ggplot(aes(x = df$Time, y = df$Price), data = df) +
        geom_line() +
        geom_point(aes(color = Action),size = 2) +
        theme_bw() +
        labs(title = paste0("validation ",i), x = "Input", y = "Price")
  print(g)
  prof_vec = c(prof_vec, df$Profit[length(df$Profit)-1])
}
hist(prof_vec, breaks = 20)

```

